// static-data.js — embedded movie data for static/Netlify deployments
// When backend is unavailable, this module serves movies from local data

const STATIC_MOVIES = [
  { id:1, title:"Vikram", year:2022, genre:["Action","Thriller"], mood:["Intense","Exciting"], pace:"Fast", hero_type:"Mass Hero", ending:"Triumphant", description:"A special agent investigates a series of murders involving masked criminals. Kamal Haasan delivers a powerhouse performance in this action-packed blockbuster directed by Lokesh Kanagaraj.", poster:"https://upload.wikimedia.org/wikipedia/en/9/93/Vikram_2022_poster.jpg", trailer:"https://youtu.be/OsLCY3vz3t8?si=VYZWq-2BX78LSZMF", rating:8.4, director:"Lokesh Kanagaraj", cast:["Kamal Haasan","Vijay Sethupathi","Fahadh Faasil"], tags:["action","intense","fast","mass"] },
  { id:2, title:"Master", year:2021, genre:["Action","Drama"], mood:["Intense","Exciting"], pace:"Fast", hero_type:"Mass Hero", ending:"Triumphant", description:"An alcoholic professor sent to a juvenile school faces off against a ruthless gangster who uses the school's children for his own gain. A mass entertainer with Vijay at his best.", poster:"https://en.wikipedia.org/wiki/File:Master_2021_poster.jpg", trailer:"https://www.youtube.com/embed/UTiXQcrLlv4", rating:7.7, director:"Lokesh Kanagaraj", cast:["Vijay","Vijay Sethupathi","Malavika Mohanan"], tags:["action","intense","fast","mass","feel-good"] },
  { id:3, title:"Kaithi", year:2019, genre:["Action","Thriller"], mood:["Intense","Gripping"], pace:"Fast", hero_type:"Common Man", ending:"Triumphant", description:"An ex-convict on his way to meet his daughter for the first time gets entangled in a drug bust gone wrong. A relentless, edge-of-the-seat thriller with zero songs.", poster:"https://www.themoviedb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg ", trailer:"https://www.youtube.com/embed/g79CvhHaj5I", rating:8.5, director:"Lokesh Kanagaraj", cast:["Karthi","Narain","Arjun Das"], tags:["action","thriller","intense","fast","gripping"] },
  { id:4, title:"Mersal", year:2017, genre:["Action","Drama"], mood:["Intense","Exciting"], pace:"Medium", hero_type:"Mass Hero", ending:"Triumphant", description:"Three men and a vendetta spanning across decades. Vijay in a triple role delivers magic in this stylish action drama with a strong social message.", poster:"https://image.tmdb.org/t/p/w500/7c6sTqK0fV5qYvXcX4Jt9V7H5aF.jpg", trailer:"https://www.youtube.com/embed/gQDo5QuZTaw
", rating:7.6, director:"Atlee", cast:["Vijay","Kajal Aggarwal","Samantha"], tags:["action","mass","intense","medium-pace"] },
  { id:5, title:"Bigil", year:2019, genre:["Action","Sports","Drama"], mood:["Exciting","Inspiring"], pace:"Medium", hero_type:"Mass Hero", ending:"Triumphant", description:"A gangster's son coaches a women's football team to the national championship while dealing with his past. Vijay is electrifying as both father and son.", poster:"https://image.tmdb.org/t/p/w500/8b9Qb8qXnKqzZo4PMBVXgS5aXoa.jpg", trailer:"https://www.youtube.com/embed/GR-Ui8-V2M0", rating:7.0, director:"Atlee", cast:["Vijay","Nayanthara","Jackie Shroff"], tags:["action","sports","inspiring","feel-good","mass"] },
  { id:6, title:"Leo", year:2023, genre:["Action","Thriller"], mood:["Intense","Exciting"], pace:"Fast", hero_type:"Mass Hero", ending:"Triumphant", description:"A peaceful cafe owner's hidden violent past catches up with him when criminals arrive in his mountain town. Vijay is absolutely ferocious in this stylish action thriller.", poster:"https://en.wikipedia.org/wiki/File:Leo_(2023_Indian_film).jpg", trailer:"https://youtu.be/q6e_b0NERCA?si=vkeGjjjSgWpsymgC", rating:7.1, director:"Lokesh Kanagaraj", cast:["Vijay","Trisha","Sanjay Dutt"], tags:["action","thriller","intense","fast","mass"] },
  { id:7, title:"96", year:2018, genre:["Romance","Drama"], mood:["Nostalgic","Emotional"], pace:"Slow", hero_type:"Sensitive Man", ending:"Bittersweet", description:"Two childhood sweethearts meet after 22 years and reminisce about their past. A deeply moving and poetic love story that lingers in your heart forever.", poster:"https://en.wikipedia.org/wiki/File:%2796_film_poster.jpg", trailer:"https://www.youtube.com/embed/r0synl-lI4I", rating:8.5, director:"C. Prem Kumar", cast:["Vijay Sethupathi","Trisha"], tags:["romance","emotional","nostalgic","slow","beautiful"] },
  { id:8, title:"Vinnaithaandi Varuvaayaa", year:2010, genre:["Romance","Drama"], mood:["Romantic","Dreamy"], pace:"Medium", hero_type:"Young Lover", ending:"Bittersweet", description:"A young man falls deeply in love with his neighbor, a Christian girl whose family disapproves. A timeless romantic classic with A.R. Rahman's unforgettable music.", poster:" https://en.wikipedia.org/wiki/File:Vinnaithaandi_Varuvaaya_poster.jpg", trailer:"https://www.youtube.com/embed/KmPOJPWfQz4", rating:8.1, director:"Gautham Menon", cast:["Silambarasan","Trisha"], tags:["romance","dreamy","medium-pace","classic-romance"] },
  { id:9, title:"OK Kanmani", year:2015, genre:["Romance","Drama"], mood:["Romantic","Feel-Good"], pace:"Medium", hero_type:"Young Lover", ending:"Happy", description:"Two career-driven young people decide to live together without marriage, while witnessing a couple's old-age love story. A refreshingly modern take on love and relationships.", poster:"https://en.wikipedia.org/wiki/File:Okay_Kanmani_film_poster.jpg", trailer:"https://youtu.be/gZZTtlpF6NE?si=a4-jL_w_AnGNN1aB", rating:7.8, director:"Mani Ratnam", cast:["Dulquer Salmaan","Nithya Menen"], tags:["romance","feel-good","modern","medium-pace"] },
  { id:10, title:"Love Today", year:2022, genre:["Romance","Comedy"], mood:["Fun","Romantic"], pace:"Fast", hero_type:"Young Lover", ending:"Happy", description:"A couple must exchange phones for a day per the girl's father's condition for marriage approval. A hilarious and heartwarming look at modern relationships and social media.", poster:" https://en.wikipedia.org/wiki/File:Love_Today_2022_poster.jpg", trailer:"https://www.youtube.com/embed/R6343uT7yt8", rating:7.6, director:"Pradeep Ranganathan", cast:["Pradeep Ranganathan","Ivana"], tags:["romance","comedy","fun","modern","feel-good"] },
  { id:11, title:"Don", year:2022, genre:["Comedy","Action","Feel-Good"], mood:["Fun","Exciting"], pace:"Fast", hero_type:"Young Hero", ending:"Happy", description:"A carefree college student with big dreams gets caught in a dangerous game of deceit and comedy. Sivakarthikeyan at his absolute best with non-stop entertainment.", poster:"https://image.tmdb.org/t/p/w500/6bq1xJ9W4wR1vE9sDcV1YxAECEV.jpg", trailer:"https://www.youtube.com/embed/s5ak-NY6OC8", rating:7.2, director:"Cibi Chakaravarthi", cast:["Sivakarthikeyan","Priyanka Arul Mohan"], tags:["comedy","action","fun","fast","feel-good"] },
  { id:12, title:"Oh My Kadavule", year:2020, genre:["Romance","Comedy","Drama"], mood:["Feel-Good","Fun"], pace:"Medium", hero_type:"Common Man", ending:"Happy", description:"A man unhappy with his marriage gets a chance to go back in time and choose a different girl. A heartwarming, funny, and beautifully honest film about love and choice.", poster:"https://en.wikipedia.org/wiki/File:Oh_My_Kadavule_poster.jpg", trailer:"https://youtu.be/5lUWBM2uYaQ?si=qX_cVVpl29OahlqE", rating:7.6, director:"Ashwath Marimuthu", cast:["Ashok Selvan","Ritika Singh","Vani Bhojan"], tags:["romance","comedy","feel-good","medium-pace"] },
  { id:13, title:"Doctor", year:2021, genre:["Action","Comedy","Thriller"], mood:["Fun","Exciting"], pace:"Fast", hero_type:"Common Man", ending:"Happy", description:"A doctor goes undercover to rescue his niece from an organ trafficking ring. Sivakarthikeyan shines in this fun action-comedy.", poster:"https://image.tmdb.org/t/p/w500/9zqU7zK1G4E0C5EvhczHxVh9Yx8.jpg", trailer:"https://www.youtube.com/embed/oQiH_Iw0kDs", rating:7.5, director:"Nelson Dilipkumar", cast:["Sivakarthikeyan","Priyanka Arul Mohan","Vinay Rai"], tags:["action","comedy","fun","fast","feel-good"] },
  { id:14, title:"Pariyerum Perumal", year:2018, genre:["Drama","Social"], mood:["Emotional","Intense"], pace:"Medium", hero_type:"Common Man", ending:"Triumphant", description:"A first-generation law student from a lower caste struggles against systemic discrimination while falling in love with a classmate. A powerful, heart-wrenching masterpiece.", poster:"https://en.wikipedia.org/wiki/File:Pariyerum_Perumal.jpg", trailer:"https://www.youtube.com/embed/GMNsUxJe4R4", rating:8.7, director:"Mari Selvaraj", cast:["Kathir","Anandhi"], tags:["emotional","social","intense","medium-pace","powerful"] },
  { id:15, title:"Asuran", year:2019, genre:["Drama","Action","Social"], mood:["Emotional","Intense"], pace:"Medium", hero_type:"Common Man", ending:"Bittersweet", description:"A downtrodden farmer protects his family from upper-caste oppression across two timelines. Dhanush gives the performance of a lifetime in this raw, powerful film.", poster:"https://en.wikipedia.org/wiki/File:Asuran_2019_poster.jpg", trailer:"https://www.youtube.com/embed/vOCM9wztBYQ", rating:8.5, director:"Vetrimaaran", cast:["Dhanush","Manju Warrier","Pasupathy"], tags:["emotional","drama","intense","powerful","social"] },
  { id:16, title:"Deiva Thirumagal", year:2011, genre:["Drama","Family"], mood:["Emotional","Heartwarming"], pace:"Slow", hero_type:"Sensitive Man", ending:"Happy", description:"A mentally challenged father fights a custody battle for his daughter. Vikram delivers an extraordinarily sensitive and heart-melting performance in this tearjerker.", poster:"https://en.wikipedia.org/wiki/File:Deiva_Thirumagal.jpg", trailer:"https://youtu.be/osY54GT0T_8?si=LnVRw7-PqAYN37XV", rating:7.8, director:"A.L. Vijay", cast:["Vikram","Anushka Shetty","Sara Arjun"], tags:["emotional","family","heartwarming","slow","tearjerker"] },
  { id:17, title:"Pizza", year:2012, genre:["Horror","Thriller"], mood:["Scary","Gripping"], pace:"Medium", hero_type:"Common Man", ending:"Twist", description:"A pizza delivery boy encounters paranormal events at a deserted bungalow. A landmark Tamil horror film that launched the genre to new heights with a brilliant twist ending.", poster:"https://en.wikipedia.org/wiki/File:Pizza_2012_poster.jpg", trailer:"https://youtu.be/1ORbkrHs5JU?si=stFjnHMtLKEynoWF", rating:7.8, director:"Karthik Subbaraj", cast:["Vijay Sethupathi","Remya Nambeesan"], tags:["horror","thriller","scary","twist","medium-pace"] },
  { id:18, title:"Demonte Colony", year:2015, genre:["Horror"], mood:["Scary","Intense"], pace:"Medium", hero_type:"Common Man", ending:"Shocking", description:"A group of friends enter a notorious haunted colony as a dare and face terrifying supernatural events. One of Tamil cinema's scariest and most atmospheric horror films.", poster:"https://en.wikipedia.org/wiki/File:Demonte_Colony.jpg", trailer:"https://youtu.be/so6-G5pfmtM?si=lBMFsNLvrc4oRcQt", rating:7.4, director:"R. Ajay Gnanamuthu", cast:["Arulnithi","Ramesh Thilak"], tags:["horror","scary","intense","medium-pace"] },
  { id:19, title:"Boss Engira Bhaskaran", year:2012, genre:["Comedy","Romance"], mood:["Fun","Romantic"], pace:"Fast", hero_type:"Mass Hero", ending:"Happy", description:"A rowdy who never wins a fight falls for a girl who wants a brave man. Non-stop comedy with Arya and Nayanthara's irresistible chemistry.", poster:"https://en.wikipedia.org/wiki/File:Boss_Engira_Bhaskaran.jpg", trailer:"https://youtu.be/XRpLTu9Cj2U?si=-J5I1ZOZC1A8B3wF", rating:7.2, director:"M. Rajesh", cast:["Arya","Nayanthara","Santhanam"], tags:["comedy","fun","romance","fast"] },
  { id:20, title:"Baasha", year:1995, genre:["Action","Drama"], mood:["Intense","Iconic"], pace:"Medium", hero_type:"Mass Hero", ending:"Triumphant", description:"A retired don living a simple life is forced to return to his violent past to protect his family. Rajinikanth's most iconic performance — the original mass hero film.", poster:"https://en.wikipedia.org/wiki/File:Baashha_poster.jpg", trailer:"https://youtu.be/y9KrRH8Pk3A?si=DweXBlQK9JZe4xTU", rating:8.1, director:"Suresh Krissna", cast:["Rajinikanth","Nagma","Raghuvaran"], tags:["action","classic","mass","iconic","intense"] },
  { id:21, title:"Padayappa", year:1999, genre:["Drama","Action"], mood:["Intense","Epic"], pace:"Medium", hero_type:"Mass Hero", ending:"Triumphant", description:"A proud, principled man fights against injustice and a vindictive woman who destroys his family. Rajinikanth's most complete performance in one of Tamil cinema's greatest classics.", poster:"https://en.wikipedia.org/wiki/File:Padayappa.jpg", trailer:"https://youtu.be/8U9t5xMElN0?si=OCA-_39RzmhQZKum", rating:7.9, director:"K.S. Ravikumar", cast:["Rajinikanth","Ramyakrishna","Sonali Bendre"], tags:["classic","drama","action","epic","intense"] },
  { id:22, title:"Nayakan", year:1987, genre:["Crime","Drama"], mood:["Epic","Emotional"], pace:"Slow", hero_type:"Complex Villain-Hero", ending:"Tragic", description:"The rise and fall of a Tamil don who shelters the oppressed in Dharavi. Kamal Haasan's greatest performance — a Tamil Godfather that remains an all-time masterpiece.", poster:"https://en.wikipedia.org/wiki/File:Nayakan_poster.jpg", trailer:"https://www.youtube.com/embed/1S6YkmYvgi8", rating:8.6, director:"Mani Ratnam", cast:["Kamal Haasan","Saranya","Delhi Ganesh"], tags:["classic","crime","epic","emotional","slow","masterpiece"] },
  { id:23, title:"Kanaa", year:2018, genre:["Sports","Drama","Feel-Good"], mood:["Inspiring","Feel-Good"], pace:"Medium", hero_type:"Young Hero", ending:"Triumphant", description:"A young woman aspires to be a cricketer despite her humble background. An uplifting, feel-good sports drama that celebrates female empowerment and family bonds.", poster:"https://en.wikipedia.org/wiki/File:Kanaa_Movie_Poster.jpg", trailer:"https://youtu.be/_6_8uzD3EYM?si=91jwvbOoasmlBIKp", rating:7.4, director:"Arunraja Kamaraj", cast:["Aishwarya Rajesh","Sathyaraj","Darshan Kumaar"], tags:["sports","inspiring","feel-good","medium-pace","family"] },
  { id:24, title:"Raja Rani", year:2013, genre:["Romance","Drama"], mood:["Emotional","Romantic"], pace:"Medium", hero_type:"Sensitive Man", ending:"Bittersweet", description:"Two people with painful romantic pasts are forced to marry each other. An emotionally rich and beautifully crafted love story about healing and second chances.", poster:"https://en.wikipedia.org/wiki/File:Raja_Rani_2013_poster.jpg", trailer:"https://www.youtube.com/embed/wZm38_0aIXk", rating:7.8, director:"Atlee", cast:["Arya","Nayanthara","Jai","Nazriya Nazim"], tags:["romance","emotional","medium-pace","feel-good"] },
  { id:25, title:"Theri", year:2016, genre:["Action","Drama","Family"], mood:["Intense","Emotional"], pace:"Medium", hero_type:"Mass Hero", ending:"Triumphant", description:"A supercop hiding his identity raises his daughter alone while being hunted by a criminal. Vijay's most balanced mass film — thrilling action meets heartfelt family drama.", poster:"https://image.tmdb.org/t/p/w500/8U0qJ9XqJ3QXyYx7Vn6s3wP5Q0O.jpg", trailer:"https://www.youtube.com/embed/ZK4uGLpkAKk", rating:7.5, director:"Atlee", cast:["Vijay","Samantha","Amy Jackson"], tags:["action","family","emotional","medium-pace","mass"] },
  { id:26, title:"Sillunu Oru Kadhal", year:2006, genre:["Romance","Drama"], mood:["Romantic","Emotional"], pace:"Medium", hero_type:"Common Man", ending:"Happy", description:"A married man encounters his first love and is torn between the past and present. A beautifully crafted romantic drama with A.R. Rahman's brilliant music.", poster:"https://en.wikipedia.org/wiki/File:Sillunu_Oru_Kaadhal.jpg", trailer:"https://youtu.be/bwx4B47-Qbk?si=wZVIY4b-UGYAl6sC", rating:7.2, director:"Vikraman", cast:["Suriya","Jyothika","Bhoomika"], tags:["romance","emotional","medium-pace","classic"] },
  { id:27, title:"Annamalai", year:1992, genre:["Action","Drama"], mood:["Intense","Iconic"], pace:"Medium", hero_type:"Mass Hero", ending:"Triumphant", description:"Two friends from different backgrounds — one rich, one poor — are torn apart by jealousy and betrayal. Rajinikanth's powerful mass performance in a timeless friendship saga.", poster:"https://ta.wikipedia.org/wiki/%E0%AE%AA%E0%AE%9F%E0%AE%BF%E0%AE%AE%E0%AE%AE%E0%AF%8D:%E0%AE%85%E0%AE%A3%E0%AF%8D%E0%AE%A3%E0%AE%BE%E0%AE%AE%E0%AE%B2%E0%AF%88_(%E0%AE%A4%E0%AE%BF%E0%AE%B0%E0%AF%88%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AE%9F%E0%AE%AE%E0%AF%8D).jpg", trailer:"https://youtu.be/ERn2EsJDe7w?si=ZU_Jv02uDMnRskNJ", rating:7.8, director:"Suresh Krissna", cast:["Rajinikanth","Sarath Babu","Khushbu"], tags:["classic","action","friendship","iconic","medium-pace"] },
  { id:28, title:"Aranmanai", year:2014, genre:["Horror","Comedy"], mood:["Scary","Fun"], pace:"Medium", hero_type:"Common Man", ending:"Happy", description:"A family moves into a haunted mansion and faces terrifying supernatural events. A hugely popular horror-comedy that blends scares with entertainer moments.", poster:"https://en.wikipedia.org/wiki/File:Aranmanai_4.jpg", trailer:"https://youtu.be/ijBxe70sd8M?si=f0KhxcUXWFeItE05", rating:6.8, director:"Sundar C", cast:["Sundar C","Siddharth","Andrea Jeremiah"], tags:["horror","comedy","fun","medium-pace"] },
  { id:29, title:"Kalakalappu", year:2012, genre:["Comedy","Action"], mood:["Fun","Exciting"], pace:"Fast", hero_type:"Common Man", ending:"Happy", description:"Two con men try to cheat each other and end up in increasingly hilarious situations. A laugh-a-minute entertainer with Jiiva and Shiva's brilliant comic timing.", poster:"https://en.wikipedia.org/wiki/File:Kalakalappu_poster.jpg", trailer:"https://youtu.be/0UM_FOOYVXs?si=RxVhi6d0UlqCXmEL", rating:7.1, director:"Ezhil", cast:["Jiiva","Shiva","Vimal"], tags:["comedy","fun","fast","entertainer"] },
  { id:30, title:"Beast", year:2022, genre:["Action","Comedy"], mood:["Exciting","Fun"], pace:"Fast", hero_type:"Mass Hero", ending:"Triumphant", description:"A RAW agent with PTSD is trapped in a mall hijacking and must save hostages. Pure mass entertainment with Vijay's electric screen presence.", poster:"https://en.wikipedia.org/wiki/File:Beast_2022_Indian_poster.jpg", trailer:"https://youtu.be/KUN5Uf9mObQ?si=hUbWP9u4yeR9T3Mg", rating:6.5, director:"Nelson Dilipkumar", cast:["Vijay","Pooja Hegde","Selvaraghavan"], tags:["action","comedy","fun","fast","mass"] }
];


// Recommendation engine (client-side, same logic as server)
function getRecommendation(answers) {
  const scored = STATIC_MOVIES.map(movie => {
    let score = 0;
    const tags = movie.tags || [];
    const genre = movie.genre || [];
    const mood = movie.mood || [];

    if (answers.mood==='excited' && (tags.includes('action')||tags.includes('fast'))) score+=3;
    if (answers.mood==='romantic' && (tags.includes('romance')||tags.includes('romantic'))) score+=3;
    if (answers.mood==='funny' && (tags.includes('comedy')||tags.includes('fun'))) score+=3;
    if (answers.mood==='sad' && (tags.includes('emotional')||tags.includes('tearjerker'))) score+=3;
    if (answers.mood==='scared' && (tags.includes('horror')||tags.includes('scary'))) score+=3;
    if (answers.mood==='inspired' && (tags.includes('inspiring')||tags.includes('feel-good'))) score+=3;
    if (answers.storyType==='love' && (genre.includes('Romance')||tags.includes('romance'))) score+=2;
    if (answers.storyType==='action' && (genre.includes('Action')||tags.includes('action'))) score+=2;
    if (answers.storyType==='social' && (tags.includes('social')||tags.includes('powerful'))) score+=2;
    if (answers.storyType==='comedy' && (genre.includes('Comedy')||tags.includes('comedy'))) score+=2;
    if (answers.storyType==='horror' && (genre.includes('Horror')||tags.includes('horror'))) score+=2;
    if (answers.storyType==='classic' && (tags.includes('classic')||tags.includes('iconic'))) score+=2;
    if (answers.preference==='action' && (tags.includes('action')||tags.includes('mass'))) score+=2;
    if (answers.preference==='emotional' && (tags.includes('emotional')||mood.includes('Emotional'))) score+=2;
    if (answers.pace==='fast' && movie.pace==='Fast') score+=2;
    if (answers.pace==='medium' && movie.pace==='Medium') score+=2;
    if (answers.pace==='slow' && movie.pace==='Slow') score+=2;
    if (answers.ending==='happy' && movie.ending==='Happy') score+=2;
    if (answers.ending==='triumphant' && movie.ending==='Triumphant') score+=2;
    if (answers.ending==='bittersweet' && movie.ending==='Bittersweet') score+=2;
    if (answers.ending==='twist' && (movie.ending==='Twist'||movie.ending==='Shocking')) score+=2;
    if (answers.heroType==='mass' && movie.hero_type==='Mass Hero') score+=2;
    if (answers.heroType==='common' && movie.hero_type==='Common Man') score+=2;
    if (answers.heroType==='sensitive' && movie.hero_type==='Sensitive Man') score+=2;
    if (answers.tone==='comedy' && (tags.includes('comedy')||tags.includes('fun'))) score+=2;
    if (answers.tone==='drama' && (tags.includes('powerful')||tags.includes('intense'))) score+=2;
    if (answers.watchTime==='night' && (tags.includes('horror')||tags.includes('thriller'))) score+=1;
    if (answers.watchTime==='family' && (tags.includes('family')||tags.includes('feel-good'))) score+=1;
    if (answers.watchTime==='alone' && (tags.includes('emotional')||tags.includes('romantic'))) score+=1;
    if (answers.watchTime==='friends' && (tags.includes('comedy')||tags.includes('action'))) score+=1;
    score += movie.rating * 0.3;
    return { ...movie, score };
  });
  scored.sort((a,b) => b.score - a.score);
  return { recommended: scored[0], alternatives: scored.slice(1,4) };
}
